### ISSUE TITLE
v2.0 - Tracker

### ISSUE THREAD

**Issue by fewtarius** [351ELEC/351ELEC#109]
## Required for Release
- [x] Core distribution rebase from LibreELEC 9.8.
- [x] Add update logic to check for free disk space before downloading image.
- [x] Separate 32bit userland from the 32bit core packages
- [x] Complete the migration of scripts to /usr/bin and remove them from the storage partition
- [x] Evaluate all scripts, optimizing where possible (still need to optimize several)

## Optional For Release
- [ ] Evaluate adding standalone Mupen64Plus
- [ ] Update the package tool to add package name and description (also update ES)
- [x] ~~Update the brightness key combo to make it more deliberate~~
- [ ] Investigate scraping to learn why scummvm does not scrape some games well
- [x] Investigate scraping failing on VIC-20, C128, and C16
- [x] ~~Delete Game from Select Menu (maybe)~~
- [ ] Update support for bluetooth devices

## Long Term Tasks
These tasks may not be completed in the current release and are worked from release to release until complete.
- [ ] Correct issue causing EmulationStation to ignore disabling Quick System Select

**Comment by fewtarius** [comment]
Closing and moving to the known issues tracker.
