### ISSUE TITLE
v2.1 - Tracker

### ISSUE THREAD

**Issue by fewtarius** [351ELEC/351ELEC#179]
# Nice to Have
- [ ] Update the package tool to add package name and description (also update ES)
- [ ] Develop replacement for setsettings.sh
- [ ] Add TATE mode config to EmulationStation menu
- [ ] Update Solarus with gamepad patch
- [ ] Update to latest OpenBOR version
- [x] Add a solution to clean ._ files (#186)
- [ ] Correct the retroachievements special character in password issue, and in the WIFI SSID.  Also check the screen scraper to see if there's an issue there as well.
- [ ] Fix MP3 BGM support
- [ ] Consolidate bbs and carts directory for Pico-8
- [ ] Fix build issues with vecx, pcsx_rearmed, and easyrpg
# Won't Do
- [x] ~~Investigate ability to configure a shader to Cave Story port or move to native core~~
- [x] ~~Relabel Auto Save/Load to Save Management, and hide the option if it's "off".~~
- [x] ~~Add "shutdown" screensaver.~~
- [x] ~~Update support for bluetooth devices~~
- [x] ~~Add network proxy support~~
- [x] ~~Look to add rumble support to more emulators~~
- [x] ~~Investigate improvements to overlay support~~
- [x] ~~Add moonlight config to EmulationStation menu~~
- [x] ~~Evaluate adding standalone Mupen64Plus~~
- [x] ~~[Reverse user decides on conflicts deprecation](https://github.com/batocera-linux/batocera-emulationstation/commit/248e57086bf8f2f6064680b221344593892b5699)~~
- [x] ~~Screenshots don’t work with Retroachievements~~

**Comment by anthonycaccese** [comment]
Nice to have: look at adding Sonic 1,2,CD de-compilations to ports. Upstream emuelec commit for reference: https://github.com/EmuELEC/EmuELEC/commit/a744c86f7bc9e1f981435d76747eaa97f473d969

**Comment by szalik-rg351** [comment]
Nice to have: Moonlight

**Comment by anthonycaccese** [comment]
Nice to have: fix Saturn (which last worked in 1.0.5)

**Comment by SmirksAlot351** [comment]
Certain manuals don’t display properly and only display as a white screen (example: SWM and LTTP on SNES)

**Comment by SmirksAlot351** [comment]
Nice to have: add MP3 support for BGM

**Comment by anthonycaccese** [comment]
Nice to have: 
update Daphne default controls and change...
select = coin
start = start
r2 = exit

**Comment by fewtarius** [comment]
Will be reworked, closing for now.
